# Используем официальный образ Python
FROM python:3.9-slim

# Устанавливаем рабочую директорию
WORKDIR / dashapp

# Копируем зависимости
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем исходный код
COPY . .

# Открываем порт, на котором будет работать Dash
EXPOSE 8051

# Команда для запуска Dash-приложения
CMD ["python", "dashapp.py"]